-- ISNULL 
-- Q1 ANSWER
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE ISNULL(NAME);

-- Q2 ANSWER
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NOT ISNULL(NAME);

-- Q3 ANSWER
SELECT ANIMAL_TYPE, IFNULL(NAME, 'No name'), SEX_UPON_INTAKE FROM ANIMAL_INS ORDER BY ANIMAL_ID;

-- JOIN
-- Q1 ANSWER
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME 
FROM ANIMAL_OUTS LEFT JOIN ANIMAL_INS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID 
WHERE ANIMAL_INS.ANIMAL_ID IS NULL;

-- Q2 ANSWER
SELECT INS.ANIMAL_ID, INS.NAME 
FROM ANIMAL_INS INS JOIN ANIMAL_OUTS OUTS 
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID 
WHERE INS.DATETIME > OUTS.DATETIME 
ORDER BY INS.DATETIME;

-- Q3 ANSWER
SELECT INS.NAME, INS.DATETIME 
FROM ANIMAL_INS INS LEFT JOIN ANIMAL_OUTS OUTS 
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID 
WHERE OUTS.ANIMAL_ID IS NULL 
ORDER BY INS.DATETIME LIMIT 3;

-- Q4 ANSWER
SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME 
FROM ANIMAL_OUTS OUTS LEFT JOIN ANIMAL_INS INS 
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE = 'Intact Male' AND OUTS.SEX_UPON_OUTCOME = 'Neutered Male' 
OR INS.SEX_UPON_INTAKE = 'Intact Female' AND OUTS.SEX_UPON_OUTCOME = 'spayed Female'
ORDER BY INS.ANIMAL_ID; 

-- String, Date
-- Q1 ANSWER
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS 
WHERE NAME = 'Lucy' 
OR NAME = 'Ella' 
OR NAME = 'Pickle' 
OR NAME = 'Rogan' 
OR NAME = 'Sabrina' 
OR NAME = 'Mitty';

-- Q2 ANSWER
SELECT ANIMAL_ID, NAME 
FROM ANIMAL_INS 
WHERE NAME LIKE '%el%' AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME;

-- Q3 ANSWER
SELECT OUTS.ANIMAL_ID, OUTS.NAME 
FROM ANIMAL_OUTS OUTS 
LEFT JOIN ANIMAL_INS INS ON OUTS.ANIMAL_ID = INS.ANIMAL_ID 
ORDER BY DATEDIFF(OUTS.DATETIME, INS.DATETIME) DESC LIMIT 2;

-- Q4 ANSWER
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, "%Y-%m-%d") 
FROM ANIMAL_INS ORDER BY ANIMAL_ID;